### ISSUE TITLE
Not a issue but would like to help

### ISSUE THREAD

**Issue by jett948** [smarky-at/Dell-XPS-9700-macOS#1]
I have my own configuration I would like to help contriubute. Not sure how you can reach out to me but would like to offer my config. I have the SD card reader working.

**Comment by smarky-at** [comment]
Hello.

This is great news! I struggled with that one and was about to ask the community for help but haven't had the time yet. Thanks for reaching out.

There are multiple ways you can help.

## 1. Forking my repository

The best and intended way would be forking the repository ([Fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)). This way not only will there be a duplicate on github (in case my account would cease to exist) but the contribution would also be visible.
Don't get too overwhelmed by the documentation, it basically boils down to:

1. Fork the repo
2. Clone via HTTPS (to have it locally)
3. Make changes
4. Commit & Push the changes
5. Create a Pull request (this will merge it to my repository)

## 2. Let me perform the changes

You can either send me the whole EFI or only the differences via this ticket and I will merge it into this repository in case working with forks is too hard. Please note that the attachment size limit for ZIP files is 25MB, so you may need to split the ZIP archive or ZIP subfolder separately.
You could also upload it to a filehost and post the link here.

Regards

**Comment by smarky-at** [comment]
After updating OpenCore, Kexts & macOS to Ventura the SD card now works.
So I will close this issue (also didn't get any reply).
