### ISSUE TITLE
My XPS15 9500's speakers will work, will their solution be similar?

### ISSUE THREAD

**Issue by excswallow** [smarky-at/Dell-XPS-9700-macOS#2]
My XPS15 9500's speakers will work, will their solution be similar?

**Comment by excswallow** [comment]
Because it was found that the 9700 could select the RTX2060 output screen in the BIOS to an external monitor, I wanted to switch from 9500 to 9700

**Comment by smarky-at** [comment]
Hi, thank you for the hint. I actually have the RTX 2060 version of the Dell XPS 9700, but I couldn't find any information on the internet about that.
Can you point me to some sources?

**Comment by excswallow** [comment]
This is just a guess I'm making because the 9500 and 9700 models are very similar and I assume they have similar sound cards. I don't know anything about writing code, and the efi I'm using is from another github user: https://github.com/zspherez/Dell-XPS-9500-4K-UHD-Monterey. I hope his solution will help you.

**Comment by smarky-at** [comment]
Thanks a lot, I will have a look at it the next few days and will update the repository accordingly if I get any progress.
